from enum import Enum
from typing import Any

from pydantic import BaseModel


class CodeEnum(str, Enum):
    ...

class Evaluation(BaseModel):
    id: int = ...
    code: CodeEnum = ...
    evaluations: dict[str, Any] = ...
    professor_id: int = ...
    subject_id: int = ...
