from pydantic import PostgresDsn
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    title: str = ...
    version: str = ...
    description: str = ...
    environment: str = ...

    postgresql: PostgresDsn = ...


settings = Settings()
